### ISSUE TITLE
Documentation on raw GraphQL requests is wrong

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-content-feedback#10]
**Article Title (if relevant)**
GraphQL Requests (JavaScript)
https://www.prisma.io/docs/prisma-client/features/graphql-requests-JAVASCRIPT-pyl3/

**Describe the content issue**
The article describes how to use `prisma.request`, and also refers to it as `prisma.$request`, but neither works.

**Describe the solution you'd like to see**
Once the feature is implemented, the syntax should be correctly implemented. It's probably `prisma.$graphql`.

**Additional context**

**Comment by martinseanhunt** [comment]
Is this feature currently not in place? If not, it's not clear at all from the docs.
