### ISSUE TITLE
Pagination, some examples are wrong

### ISSUE THREAD

**Issue by Vadorequest** [prisma/prisma-content-feedback#101]
**Article Title (if relevant)**
https://www.prisma.io/docs/1.27/prisma-graphql-api/reference/queries-qwe1/#pagination

**Describe the content issue**
Several examples don't match the source code and the given exaplanation

**Describe the solution you'd like to see**
Doc must be fixed

**Additional context**
![image](https://user-images.githubusercontent.com/3807458/58336193-93421180-7e43-11e9-88e1-4ad99c8f04c8.png)
![image](https://user-images.githubusercontent.com/3807458/58336204-9b9a4c80-7e43-11e9-84ee-d5dfaf1b5d9f.png)

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @Vadorequest. You are viewing an old version (1.27) of the docs, the latest version as of today is [1.33](https://www.prisma.io/docs/1.33).

We have actually removed the "GraphQL API docs" that contained this error, if you're interested in what pagination looks like with the Prisma client you can go [here](https://www.prisma.io/docs/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2/#pagination). You can read why we removed the docs [here](https://github.com/prisma/prisma-content-feedback/issues/69).

May I ask how you ended up on that site? We are aware that our docs currently don't have the best SEO and googling for Prisma-related functionality often doesn't lead to the best results. We are actively working on improving the SEO for the docs, so hopefully you'll have an easier time finding relevant docs in the future! 🙏 

Unfortunately, we are not actively maintaining older docs versions from more than 3 releases ago and therefore won't fix the error. However, I'll be happy to merge a PR if you want to take a stab at fixing the issue 🙂

**Comment by Vadorequest** [comment]
I looked up how I arrived there but couldn't figure it out, unfortunately.

There is no point fixing outdated docs, especially 6 versions old, so I won't make a PR. But I appreciate you taking the time for explaining it all. :)
