### ISSUE TITLE
Blog: objectType('Query') for Mutation

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma-content-feedback#105]
**Blog Post**
[The Problems of "Schema-First" GraphQL Server Development](https://www.prisma.io/blog/the-problems-of-schema-first-graphql-development-x1mn4cb0tyl3)

**Describe the content issue**
Contains this code:
```javascript
const Mutation = objectType('Query'
```

**Describe the solution you'd like to see**
Should be this?
```javascript
const Mutation = objectType('Mutation'
```

**Comment by nikolasburk** [comment]
Thanks for catching this Martin, I just deployed a fix 🙌
