### ISSUE TITLE
Blog: objectType or query/mutationType?

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma-content-feedback#107]
**Blog Post**
[Introducing GraphQL Nexus: Code-First GraphQL Server Development](https://www.prisma.io/blog/introducing-graphql-nexus-code-first-graphql-server-development-ll6s1yy5cxl5/)

**Describe the content issue**
In the blog post linked above (a follow-up blog post to #105) it says:
```javascript
const Query = queryType({
const Mutation = mutationType({
```
Yet the official [Nexus repo](https://github.com/prisma/nexus/search?q=Query+%3D+objectType&unscoped_q=Query+%3D+objectType) defines a query and mutation like this:
```js
const Query = objectType({
const Mutation = objectType({
```

So confused: which is which?

**Comment by nikolasburk** [comment]
Hey Martin, sorry if the docs don't make this clear. `queryType` and `mutationType` are shortcuts for:

```js
const Query = objectType({
  name: 'Query',
  // ...
})
```

```js
const Mutation = objectType({
  name: 'Mutation',
  // ...
})
```
