### ISSUE TITLE
Two problems with upgrade guide

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-content-feedback#11]
**Article Title (if relevant)**
Maintain
https://www.prisma.io/docs/maintain

**Describe the content issue**
![image](https://user-images.githubusercontent.com/1780597/46790440-3e7fd980-cd3f-11e8-8c7e-c6707df557f1.png)

> first the link "upgrade to 1.17" points to "upgrade to 1.16"
> second, when the link is opened in a new tab I go to an error page...

**Describe the solution you'd like to see**
The guide is consistently called `1.17` or `1.16` and does not error when being viewed.

**Comment by nikolasburk** [comment]
Thanks Nilan! The first issue is fixed, the overview page now correctly points to 1.16. The second issue is already reported [here](https://github.com/prisma/prisma-docs-v2/issues/29) (original issue was [here](https://github.com/prisma/prisma-content-feedback/issues/5#issuecomment-428508139)), so I'm closing this issue.
