### ISSUE TITLE
Can we use directly imported prisma client in our resolvers?

### ISSUE THREAD

**Issue by nagman** [prisma/prisma-content-feedback#115]
**Article Title (if relevant)**
[Configure your GraphQL server](https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-TYPESCRIPT-t201/#configure-your-graphql-server)

**Describe the content issue**
It says the following:
`You're also attaching the imported prisma client instance to the context so that the resolvers can access it.`
```
const server = new GraphQLServer({
  schema,
  context: { prisma },
})
server.start(() => console.log('Server is running on http://localhost:4000'))
```

**Describe the solution you'd like to see**
Why should we pass the prisma client to the context of the resolvers, as we can import prisma where we want?

I mean, can't we directly use `import { prisma } from './generated/prisma-client';` into the resolvers' files?
It would be easier to access the prisma instance for queries and mutations.

Maybe is it faster, or more optimized with one single import of prisma, but I'd like explanations.
Because in some cases, I can't access the context (e.g. a node-cron task apart from the GraphQL API), and I import prisma separately. And it works very well.  
So I wondered if I could remove prisma from the context and import it into each of my resolvers.

**Comment by jpvanoosten** [comment]
The generated prisma client always creates a new client:
```javascript
exports.prisma = new exports.Prisma();
```
If you imported that into your resovers, each resolver file would get a new instance.

**Comment by nagman** [comment]
Ok. So it's better to import the least instances in order to improve performance, I guess?

**Comment by jpvanoosten** [comment]
Each new instance creates a database connection, so it probably a good idea to have only 1 per request.

**Comment by jwld** [comment]
@jpvanoosten is this definitely the case? Finding [contradicting advice](https://stackoverflow.com/questions/55571978/is-better-pass-prisma-object-through-context-to-resolvers-or-use-it-directly) on this so I want to be sure.

It doesn't create a singleton in this situation?

**Comment by jpvanoosten** [comment]
@jwld In the general case, I believe that it is true that modules are only included once. In this case, there should be only a single instance of the Prisma client but this is not always guaranteed to be the case. This better described here: [Are Node.js modules singletons?](https://medium.com/@lazlojuly/are-node-js-modules-singletons-764ae97519af)

It's good to know when you can break the module singleton rule.

**Comment by jwld** [comment]
@jpvanoosten Ok, thanks for that article, very useful! So the prisma export should be cached (and not create a new connection), as long as you make sure you're importing from the same file and with the same casing each time?

**Comment by nagman** [comment]
@jwld It seems like we actually can import the same instance of prisma in all our files from the generated file. I've made a test:

**index.ts**
```typescript
import { prisma, prisma2 } from './generated/prisma-client';
import { foo } from './test';

console.log(prisma === prisma2); // false
console.log(prisma === foo); // true
```

**test.ts**
```typescript
import { prisma } from './generated/prisma-client';

export const foo = prisma;
```

**generated/prisma-client.ts**
```typescript
// [...]
export const prisma = new Prisma();
export const prisma2 = new Prisma();
```
