### ISSUE TITLE
Code example in "Implement GraphQL API based on CRUD building blocks" has prismaObjectType missing error

### ISSUE THREAD

**Issue by ralitong** [prisma/prisma-content-feedback#129]
**Article Title (if relevant)**
[Implement GraphQL API based on CRUD building blocks](https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-TYPESCRIPT-t201/#implement-graphql-api-based-on-crud-building-blocks)

**Describe the content issue**
prismaObjectType not found in nexus-prisma library

**Describe the solution you'd like to see**
Include the package.json to download the correct library versions

**Additional context**
<img width="960" alt="Screen Shot 2020-01-11 at 18 49 59" src="https://user-images.githubusercontent.com/31039855/72203171-842bd480-34a3-11ea-9ec3-011e881177b3.png">

package.json
```
{
  "name": "prisma-getting-started",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "ts-node index.ts",
    "dev": "ts-node-dev --no-notify --respawn --transpileOnly ./"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "graphql": "^14.5.8",
    "graphql-yoga": "^1.18.3",
    "nexus": "^0.12.0-rc.5",
    "nexus-prisma": "^0.6.1",
    "prisma-client-lib": "^1.34.10"
  },
  "devDependencies": {
    "ts-node": "^8.6.1",
    "ts-node-dev": "^1.0.0-pre.44",
    "typescript": "^3.7.4"
  }
```

**Comment by tiagoboeing** [comment]
I have same problem. It turns out that the docs are deprecated, I opened [this issue](https://github.com/prisma/prisma-content-feedback/issues/131).

You can replace:
- `prismaObjectType` → `objectType`
- `makePrismaSchema` → `makeSchema`

**Comment by ralitong** [comment]
I think this issue could be close since the breaking changes in prisma is mentioned in issue #128
