### ISSUE TITLE
Using graphql-import with Prisma v1.18

### ISSUE THREAD

**Issue by vctormb** [prisma/prisma-content-feedback#14]
**Article Title (if relevant)**
Article: [Datamodel & Migrations - A note on the app schema](https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/#a-note-on-the-application-schema)

**Describe the content issue**
When using Prisma CLI and deploying the app, the schema is generated inside the folder ``generated/prisma/index.js``.  
**The issue is:** in the example on how to use ``graphql-import`` you need to import from ``prisma.graphql`` file, and in the v1.18 it is generating a ``.js`` file.  
How can I import the ``prisma.schema`` from this ``.js`` file?

**Describe the solution you'd like to see**
A link redirecting to [Configuring generate in prisma.yml](https://www.prisma.io/docs/1.18/prisma-client/setup/generating-the-client-rsc1/) indicating that you can generate a prisma.graphql file by modifying the ``prisma.yml`` file.

**Comment by etelsv** [comment]
Thanks for opening this issue. We are going to address this over the next few days :)

**Comment by nikolasburk** [comment]
Thanks for reporting this @vctormb, I've added a not to the [article](https://www.prisma.io/docs/1.19/data-model-and-migrations/data-model-knul/#a-note-on-the-application-schema) linking to the client generation page 🙌
