### ISSUE TITLE
AWS Fargate tutorial is Incomplete/Outdated (can't connect to prisma cloud)

### ISSUE THREAD

**Issue by harrisrobin** [prisma/prisma-content-feedback#16]
**Article Title (if relevant)**
https://www.prisma.io/tutorials/deploy-prisma-to-aws-fargate-ct14

**Describe the content issue**
Following the AWS Fargate tutorial, while everything works fine I am unable to connect my Prisma server to Prisma Cloud, despite the fact that `Step 30` suggests the following:

> You can also manage your AWS Fargate server through the free Prisma Cloud Connect. Watch this 4min-video for more info.

<img width="580" alt="screen shot 2018-11-07 at 1 37 28 pm" src="https://user-images.githubusercontent.com/3880008/48152632-64db5b00-e292-11e8-983b-eb487a55121a.png">

**Describe the solution you'd like to see**
I would like to see the missing steps in order to be able to manage my Prisma servers that are on AWS Fargate from Prisma Cloud.

**Additional context**
Pinging @divyenduz as he asked me to add this issue following our conversation.

**Comment by etelsv** [comment]
Hey Harris!

Thank you so much for sharing this issue. I just ran through the tutorial myself from scratch and was able to set up the connection. A couple thoughts:

- Are you able to connect to the AWS service without Prisma cloud? Is the issue connecting through the cloud interface?

- Are all of the credentials correct: passwords, endpoints, etc. If you used credentials that differed from the example credentials in the tutorial, did you substitute in yours in all of the necessary steps? 

Additionally, you can also potentially get additional insight by checking the relevant logs. You can access those by going to the AWS services in the top navigation bar, clicking on "Cloudwatch"
<img width="1435" alt="screenshot 2018-11-11 at 14 53 13" src="https://user-images.githubusercontent.com/42931286/48313858-3fb45880-e5c2-11e8-82d9-130ac85da807.png"> and then selecting the "Logs" option on the left side. Clicking through to your Prisma server will give you additional details on the steps taken by AWS. That can also potentially help debug the connection. 

If you'd like additional support debugging, you can also share the logs and we can take a look :)

**Comment by etelsv** [comment]
Hey Harris -- I updated the tutorial with additional content that covers connecting your fargate servers to Prisma cloud. Please feel free to submit any further issues if you run into any obstacles with the content. As the tutorial should now be updated, I'll close out this issue! Thanks for reaching out 😸
