### ISSUE TITLE
Demo server reference and String/JSON limitation

### ISSUE THREAD

**Issue by jorabra** [prisma/prisma-content-feedback#19]
**Article Title (if relevant)**
The Datamodel - https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/

**Describe the content issue**
Reading the documentation in cronological order the "demo server" makes no sense to me. Yes, there is a "Demo database" option in the "Get Started" section, but I chose the "New database" path. And is "Demo database" and "Demo server" the same thing? Why limit String and JSON to 256KB? I actually thought for a second that this was a general limitation with Prisma - which would be a major dealbreaker.

**Describe the solution you'd like to see**
References to "demo server" and "demo database" later in the documentation should include a info box of with information describing what they are. Some of us reading the docs would not be aware of the demo database/server.

**Comment by nikolasburk** [comment]
Thanks for opening this issue @jorabra! I've just linked every occurrence of the "Demo server" to the corresponding docs page: https://www.prisma.io/docs/prisma-server/demo-servers-prisma-cloud-jfr3/

Hopefully this make it easier to get more context on Demo servers when needed. 

As to your point to consolidate terminology around "Demo server" vs "Demo database", this has been brought up in [this](https://github.com/prisma/prisma-content-feedback/issues/6) issue as well and is high on on our TODO-list. However, this requires a bit of a bigger rethinking of the terminology that we're using overall so I'm hoping to that we're able to make some progress here over the next few weeks.
