### ISSUE TITLE
Dead "tbd" links

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-content-feedback#20]
**Article Title (if relevant)**
https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/#generated-api-operations-for-fields

**Describe the content issue**

Broken link
![image](https://user-images.githubusercontent.com/1567498/48696328-ed86bf00-ebe1-11e8-8aa5-55aa2ec65f1f.png)

**Describe the solution you'd like to see**
Working links 👀

**Comment by etelsv** [comment]
Niko addressed this :)
