### ISSUE TITLE
Prisma CLI as dev dependecy

### ISSUE THREAD

**Issue by steida** [prisma/prisma-content-feedback#21]
https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/

I believe prisma should be dev dependency. Both npm and yarn allow to run dev tools like prisma without global installation.

**Comment by nikolasburk** [comment]
Hey @steida, thanks a lot for opening this issue. We've just had a similar request to use `npx` for the [prisma-examples](https://github.com/prisma/prisma-examples/). While we have been thinking about this question _a lot_ internally, we've come to the conclusion to require global installations of the Prisma CLI for the "Getting Started"-tutorials as well as for the examples.  

I'm copy-pasting my response to the other issue for context here as well. We have decided to:

- Consistently require users to install the Prisma CLI globally
- Include all other dependencies (e.g. graphqlgen) as dev dependencies and invoke them via a script defined in package.json

The reasoning for the global installation of the Prisma CLI is that we don't want to have any abstraction between the user and the Prisma CLI, they should use it _directly_. Before reworking the examples, we included Prisma as a dev dependency and have received the feedback that it was confusing (especially for beginners) to use `yarn prisma [command]` instead or just `prisma [command]` which is seen in the docs. Another important point here is that we want all examples to be _consistent_ and _idiomatic_ to their respective language. While it's _possible_ to use `npx` for the Go-examples, it's not definitely not _idiomatic_. Go examples instruct the users to install the Prisma CLI via Homebrew and there's no way to include it as a dev dependency. 

Please let me know if you have any further questions!
