### ISSUE TITLE
prisma deploy errors out

### ISSUE THREAD

**Issue by bwobst** [prisma/prisma-content-feedback#22]
**Describe the content issue**
When following the [fullstack tutorial](https://www.prisma.io/tutorials/bootstrap-a-fullstack-graphql-app-with-react-and-apollo-cz12/) it says to run the command:
```bash
graphql create my-app --boilerplate react-fullstack-basic
```
All deps are installed successfully. `prisma deploy` runs next and attempts to `create stage dev for service my-app`.

This fails with the error:
```bash
ERROR: Project not found: 'cluster@default'

{
  "errors": [
    {
      "message": "Project not found: 'cluster@default'",
      "code": 3016,
      "requestId": "us1:cjoui8agh8iyj0a719easdw93"
    }
  ],
  "status": 200
}
```

It's not a fatal error as I see other content below it:
```bash
Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"

Next steps:
  1. Change directory: `cd my-app/server`
  2. Start local server: `yarn start` (you can now open a Playground at http://localhost:4000)
  3. Change directory: `cd ..`
  4. Start React app: `yarn start`
  5. Open browser: http://localhost:3000
```

**Describe the solution you'd like to see**
`prisma depoy` should deploy the new service

**Steps to reproduce**
1. Confirm you're logged in with `prisma account`
2. `graphql create my-app --boilerplate react-fullstack-basic`
3. You should see the error message at the end of the creation process.

**Additional context**
- I am logged in on the prisma cli
- I do not see any newly created service on app.prisma.io
- node: 8.12.0, yarn 1.12.3, prisma: 1.21.0, graphql: 2.17.0

**Comment by nikolasburk** [comment]
Hey @bwobst, thanks a lot for opening the issue. I just gave a major update to the boilerplates, so the fullstack React boilerplate should be working again. Please open another issue if you come across any other error! 🙏
