### ISSUE TITLE
Example on how to use Subscriptions with prisma-client and graphql-yoga

### ISSUE THREAD

**Issue by chris-me** [prisma/prisma-content-feedback#26]
**Article Title (if relevant)**
Realtime (JavaScript)
https://www.prisma.io/docs/prisma-client/features/realtime-JAVASCRIPT-rsc8/

**Describe the content issue**
The documentation only shows how to create an async iterator.

**Describe the solution you'd like to see**
It would be very helpful if there where an example on how to use the async iterator in conjunction with graphql-yoga server.

**Additional context**
 Tried to simply return the prisma iterator, but this did not work for me and the tutorials and how-to's I've found where not specificaly for new prisma client with its $subscribe feature.

**Comment by nikolasburk** [comment]
Hey @chris-me, thanks a lot for opening this issue. [Here](https://github.com/prisma/prisma-examples/tree/master/node/graphql) is an example that uses `graphql-yoga` and the subscriptions feature of the Prisma client.

Please let me know if you have any further questions 🙏

**Comment by chris-me** [comment]
Thank you very much, [that](https://github.com/prisma/prisma-examples/tree/master/node/graphql-subscriptions) pointed me into the right direction! 👍
