### ISSUE TITLE
Update permissions-with-shield example

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-content-feedback#3]
**Article Title (if relevant)**
`permissions-with-shield` example - https://github.com/prisma/prisma-examples/tree/master/archive/permissions-with-shield

**Describe the solution you'd like to see**
> The permissions-with-shield 3 example is using prisma-binding,could use Prisma Client instead of prisma-binding when next update?

**Additional context**
Original Forum thread https://www.prisma.io/forum/t/could-the-example-permissions-with-shield-use-prisma-client-instead-of-prisma-binding-in-next-update/4543?u=nilan

**Comment by etelsv** [comment]
This is currently being worked on internally, and we're hoping to have this change live by the end of the week.
