### ISSUE TITLE
wrong links of the doc

### ISSUE THREAD

**Issue by HaveF** [prisma/prisma-content-feedback#30]
**Article Title (if relevant)**
Provide the name and link to the article with the issue
https://www.prisma.io/docs/prisma-client/

**Describe the content issue**
A clear and concise description of what the issue with the content was
![image](https://user-images.githubusercontent.com/54462/49556944-e6c9ad00-f940-11e8-909c-e5beea302f4b.png)
wrong:
 - Prisma CLI & Configuration ->(link to) -> https://www.prisma.io/docs/prisma-client/
 - Prisma client ->(link to) ->https://www.prisma.io/docs/prisma-cli-and-configuration/

**Describe the solution you'd like to see**
How can this issue be resolved?
The two real links under the hyper-texts should be exchanged.

**Additional context**

**Comment by nikolasburk** [comment]
Hey @HaveF, thanks a lot for opening this issue. I can't seem to reproduce your issue.

When I click on **Prisma Client** in the sidenav, I see the proper page:

![image](https://user-images.githubusercontent.com/4058327/49573049-5d64ab80-f93d-11e8-84bf-cc27e0cfe45b.png)

If I click on **Prisma CLI & Configuration** in the sidenav, I also see the right page:

![image](https://user-images.githubusercontent.com/4058327/49573085-71a8a880-f93d-11e8-8377-194b6b6ab163.png)

Did I understand your issue correctly? Can you confirm your issue still exists? Maybe with a full screenshot or a GIF?

**Comment by HaveF** [comment]
left click is fine.

right click the link and open at another tab, you will see the error

**Comment by schickling** [comment]
Related: When reloading the page

![image](https://user-images.githubusercontent.com/1567498/49575721-ad467100-f943-11e8-96ca-93473c030556.png)

**Comment by schickling** [comment]
Fixed now.
