### ISSUE TITLE
[Positive Document & Typescript/MongoDB/HelloWorld Feedback] Prisma, hummm.........

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [prisma/prisma-content-feedback#31]
**Article Title (if relevant)**
Prisma Introduction: What, Why & How
https://www.prisma.io/docs/understand-prisma/prisma-introduction-what-why-how-j9ff/

**What did you find helpful in the article?*
We want to know :) 
This article did very well describing the concerns of a developer who looks to the long-term in application scale, specifically, "When developing application servers, most complexity lies in implementing a safe and well-organized database access with respect to synchronization, query optimization/performance and security." Will not expand on that well stated and simple explanation.

**Additional context**
Any additional information you want to share....

**Comment by nikolasburk** [comment]
Thanks so much for the feedback @GoodFaithParadigm8 🙏
