### ISSUE TITLE
Wrong steps order in "Set up Prisma - Existing database"

### ISSUE THREAD

**Issue by guidolodetti** [prisma/prisma-content-feedback#35]
**Article Title (if relevant)**
Set up Prisma - Existing database

**Describe the content issue**
Step 7 should be before step 6

**Describe the solution you'd like to see**
If you don't run `prisma deploy`, `prisma introspect` will fail.

**Comment by nikolasburk** [comment]
Thanks for reporting this! I just updated the Getting Started tutorial to use the `prisma init` command instead which should alleviate the issue 🙌
