### ISSUE TITLE
Documentation of many-to-many relation i lacking

### ISSUE THREAD

**Issue by axhamre** [prisma/prisma-content-feedback#37]
**Article Title (if relevant)**
https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MYSQL-knul/#relations

**Describe the content issue**
I expected to see some information on the very common many-to-many relation, but there appears to be none.

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @axhamre 🙌 I've just added an example for many-to-many relations to the datamodel docs.
