### ISSUE TITLE
Tip for using CLI from Windows Subsystem for Linux

### ISSUE THREAD

**Issue by EXPErdelfavero** [prisma/prisma-content-feedback#38]
**Article Title (if relevant)**
Up to you if this is relevant, but I was thinking this info could maybe go on "Using the Prisma CLI"

**Describe the content issue**
You're probably not familiar with Windows Subsystem for Linux, but you can think of it as a VM running Ubuntu under Windows 10. The WSL is text-only and has a separate file system from the Windows file system. So if you're using WSL on a Windows 10 machine, you only get to do command-line stuff, you don't get the full Ubuntu environment with integrated browser. Running 'prisma deploy' starts a web browser session on the Windows default browser, but that's running outside the WSL VM, and doesn't work properly. The web page gives an error message about badly formed JSON instead of guiding you through the account creation process. I've found a workaround that you might want to document somewhere.

**Describe the solution you'd like to see**
Here's the workaround:
1. Go to the Prisma Console site and create an account. Log in. Leave that window open.
2. In the WSL bash window, run `prisma login`, and grant the CLI permissions as requested in the browser window that Windows shows you. That login works, at least for me.
3. *Now* you can run `prisma deploy`, choose the Demo server, region, service and stage names.

**Additional context**
Nothing more to add. I know this is a real corner case, but thought you might find the information useful once or twice a year ;)

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @EXPErdelfavero. I've added a note to the `prisma login` page in the docs including your workaround.
