### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by EXPErdelfavero** [prisma/prisma-content-feedback#39]
**Article Title (if relevant)**
prisma deploy

**Describe the content issue**
Near the beginning of the page, 'deom' appears.

**Describe the solution you'd like to see**
I think it should be 'from'. Looks like a typo I make all the time when I place my left hand one key left of the proper home row position.

**Additional context**
I've said too much already.

**Comment by nikolasburk** [comment]
Haha, thanks a lot for catching this @EXPErdelfavero 😄 I've just fixed the ghpo.
