### ISSUE TITLE
Link broken to 'Building GraphQL Servers with Prisma'

### ISSUE THREAD

**Issue by benjamin-rood** [prisma/prisma-content-feedback#4]
**Article Title:**
**'Datamodel & Migrations / The Datamodel'**
https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/#datamodel-vs-prisma-graphql-schema

Link at bottom of 'Datamodel vs. Prisma GraphQL Schema' section to 'Building GraphQL Servers with Prisma' is broken. Currently, link points to: https://www.prisma.io/1.15/understand-prisma/building-graphql-servers-with-prisma-dvw4

**Describe the solution you'd like to see**
Update link to current version of the 'Building GraphQL Servers with Prisma' article.

**Comment by etelsv** [comment]
Thank you for letting us know. I will be addressing this, this week.

**Comment by etelsv** [comment]
The article was amended to side step this link issue.
