### ISSUE TITLE
Hyperlinks towards the issue for multiple orderBy's

### ISSUE THREAD

**Issue by Brampage** [prisma/prisma-content-feedback#42]
**Article Title (if relevant)**

[Queries](https://www.prisma.io/docs/prisma-graphql-api/reference/queries-qwe1/#query-arguments)

**Describe the content issue**

The links inside the following text should link to the issue, but the issue is not found: 

```
It's currently not possible to order responses by multiple fields or by related fields. Join the discussion in the feature requests if you're interested in these features!
```

**Describe the solution you'd like to see**

Links to join the discussion ([this](https://github.com/prisma/prisma/issues/62) is the link towards the issue).

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @Brampage 🙌 I've just fixed the links.
