### ISSUE TITLE
Fix Client constructor documentation

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-content-feedback#43]
**Article Title (if relevant)**
https://www.prisma.io/docs/prisma-client/setup/constructor-JAVASCRIPT-rsc4/

**Describe the content issue**
It mentions the class as `BasePrismaOptions` but it is `BaseClientOptions` now. It used to be `BasePrismaOptions` in binding. 

It also doesn't include `fragmentReplacements` anymore as delegation is not a feature of Client. 

**Describe the solution you'd like to see**
These should be fixed.

**Comment by nikolasburk** [comment]
Thanks Divy, just fixed it 🙌
