### ISSUE TITLE
How to rename relation

### ISSUE THREAD

**Issue by bizmedia** [prisma/prisma-content-feedback#47]
**Renaming Relations**
How to rename Relations? 
For example:  ` @relation(name: "UserPayment")` to  `@relation(name: "UserPayments")`?

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @bizmedia! Renaming relations unfortunately is not possible at the moment but will be enabled with the next version of the [datamodel v1.1](https://github.com/prisma/prisma/issues/3406) that's coming soon. I've added a note about this limitation to the migration docs.
