### ISSUE TITLE
this.schema.getQueryType is not a function

### ISSUE THREAD

**Issue by Dung-Nguyen** [prisma/prisma-content-feedback#48]
**Article Title (if relevant)**
https://www.prisma.io/docs/1.24/get-started/01-setting-up-prisma-demo-server-TYPESCRIPT-t001/

**Describe the content issue**
https://spectrum.chat/prisma/general/prisma-client-this-schema-getquerytype-is-not-function~fd50cbff-663b-47d3-a50b-e5e6959647d4

**Comment by nikolasburk** [comment]
Hey @Dung-Nguyen, thanks a lot for opening the issue 🙌 It seems like you were able to resolve the issue?! Please let us know if you're still running into any trouble!
