### ISSUE TITLE
Broken link in Get Started guide

### ISSUE THREAD

**Issue by davecalnan** [prisma/prisma-content-feedback#49]
**Article Title (if relevant)**
[Set up Prisma](https://www.prisma.io/docs/1.24/get-started/01-setting-up-prisma-new-database-TYPESCRIPT-t002/)

**Describe the content issue**
The link at the bottom of the page to continue to the next issue is incorrect. It currently links to [What happens when a prisma server crashes](
https://www.prisma.io/docs/faq/what-happens-when-a-prisma-server-crashes-fq00/).

> Great work! 👏 Move on to learn how you can change your datamodel and (re-)generate your Prisma client.
> [NEXT STEP →](https://www.prisma.io/docs/faq/what-happens-when-a-prisma-server-crashes-fq00/)

**Describe the solution you'd like to see**
Link updated to https://www.prisma.io/docs/1.24/get-started/02-change-data-model-TYPESCRIPT-t101/ (and equivalents for languages other than typescript).

**Additional context**
Screenshot 👇
<img width="773" alt="screenshot 2019-01-18 19 26 57" src="https://user-images.githubusercontent.com/23709612/51408737-af613980-1b57-11e9-9c72-247d87769d2a.png">

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @davecalnan, this has been fixed by now 🙌
