### ISSUE TITLE
Replace "aruments" with the correct "arguments" word

### ISSUE THREAD

**Issue by marcos8896** [prisma/prisma-content-feedback#50]
**Article Title (if relevant)**
[Forwarding to Prisma](https://www.prisma.io/docs/1.15/use-prisma-api/prisma-bindings/forwarding-to-prisma-onq1/)

**Describe the content issue**
There is a wrongly written word on the documentation, which is `aruments` and I think it would have to be `arguments`.

**Describe the solution you'd like to see**
Replace the word `aruments` with `arguments`

**Additional context**
![image](https://user-images.githubusercontent.com/22345533/51435895-d7c86100-1c47-11e9-92d8-1aa05ae5bf18.png)

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that our @marcos8896 🙌 I've fixed the typo. Also note that we've removed the Prisma binding docs in the newer versions of the Prisma docs (as they're not part of the Prisma core any more), so this only applies to the older Prisma docs versions.
