### ISSUE TITLE
Document use of multiple databases and relation to services + stages

### ISSUE THREAD

**Issue by jahudka** [prisma/prisma-content-feedback#51]
**[Prisma Server](https://www.prisma.io/docs/prisma-server/)**

The `databases` section of `PRISMA_CONFIG` in a `docker-compose.yml` file clearly hints at the possibility of connecting to multiple databases from the same Prisma server instance. It is, however, unclear how to actually access such a configuration from client code. How would a `datamodel.graphql` look for an app which needs to access multiple databases on the same Prisma server? What about naming conflicts? What about the use case of having a single Prisma server managing multiple databases, each of which is accessed from a different client application? How do services and stages map to databases?

I'd like to see this documented, preferably along with connector-specific differences such as schemas in Postgres (which currently work in a very non-obvious way from my point of view).

**Comment by jferrettiboke** [comment]
https://github.com/prisma/prisma/issues/2873

**Comment by jahudka** [comment]
@jferrettiboke yeah, I've seen that, but since August last year there's been no update on this - and that's just one of the use cases I was talking about. My most needed use case is having multiple independent databases for multiple independent apps through a single common Prisma server instance. I could run one docker image per app, but the added overhead just seems like such a waste. Additionally I'd really love for Prisma to start working with Postgres schemas the way it's supposed to instead of the hair-pulling nightmare it is now, but that's a different issue (albeit connected to the services and stages part of this one).

**Comment by nikolasburk** [comment]
Thanks for opening this issue @jahudka. As @jferrettiboke pointed out, this is unfortunately not yet supported by Prisma. `PRISMA_CONFIG` was designed in a way to already anticipate this future feature, so that's why we have the `databases` property specified in plural. I've added a warning to the `PRISMA_CONFIG` docs for now that this is not yet supported.
