### ISSUE TITLE
Precise and fun to read

### ISSUE THREAD

**Issue by tonymj76** [prisma/prisma-content-feedback#57]
**Article Title (if relevant)**
https://www.prisma.io/docs/1.25/datamodel-and-migrations/datamodel-POSTGRES-knum/#unique

**What did you find helpful in the article?*
everything in that page is helpful to get more familiar with prisma 

**Additional context**
i enjoy reading this page it is precise and well documented, but no mention of validation? can't wait for @constrains to be implemented.

** Validation will be Nice ** 
thanks you guy did an amazing job

**Comment by nikolasburk** [comment]
Thanks so much for the positive feedback @tonymj76 🙌
