### ISSUE TITLE
Improve the authentication docs

### ISSUE THREAD

**Issue by jlengstorf** [prisma/prisma-content-feedback#61]
The [authentication docs](https://www.prisma.io/docs/prisma-graphql-api/reference/authentication-ghd4/#example:-protecting-your-prisma-api) left me a little stuck, so I have some suggestions that would have un-stuck me.

To make it more clear how to set up authentication with a `secret` in practice:

1. Link to the [env var](https://www.prisma.io/docs/prisma-cli-and-configuration/prisma-yml-5cy7/#environment-variable) docs and call out that it's probably a good idea to use env vars
2. Mention that `prisma generate` will automatically configure the `secret` so you don't need to run `prisma token`.

Thanks!

**Comment by nikolasburk** [comment]
Thanks a lot for the feedback JSON and sorry for the delay. We've just updated the docs with these notes [here](https://www.prisma.io/docs/prisma-graphql-api/reference/authentication-ghd4/#service-secret) and [here](https://www.prisma.io/docs/prisma-client/setup/generating-the-client-rsc1/#configuring-generate-in-prisma.yml).

**Comment by jlengstorf** [comment]
> Thanks a lot for the feedback JSON Jason (🙈)

We're fighting now. 😂

Thank you!
