### ISSUE TITLE
Numbered list not render properly

### ISSUE THREAD

**Issue by katopz** [prisma/prisma-content-feedback#62]
**Article Title (if relevant)**
Provide the name and link to the article with the issue
https://www.prisma.io/docs/datamodel-and-migrations/migrations-MYSQL-asdf/

**Describe the content issue**
A clear and concise description of what the issue with the content was
Numbered list not render as sequence as it should (only 1. 1. 1. expected 1. 2. 3.)

**Describe the solution you'd like to see**
How can this issue be resolved?
Fix `mdx` or renderer I guess?

**Additional context**
![image](https://user-images.githubusercontent.com/97060/52908730-0d478500-32ae-11e9-9d79-3a46c348bff0.png)

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @katopz, it's now fixed 🙌
