### ISSUE TITLE
prisma cli - Invalid token (PRISMA_MANAGEMENT_API_SECRET)

### ISSUE THREAD

**Issue by bitIO** [prisma/prisma-content-feedback#64]
**Get Started > Set up Prisma**
https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/

**No reference to cli requirement PRISMA_MANAGEMENT_API_SECRET**
There is no single line referring to the *need* of the PRISMA_MANAGEMENT_API_SECRET environment variable to be set in order to run `prisma deploy`

**Describe the solution you'd like to see**
Link to https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/ where that line is finally stated or add it to the get started documentation

**Comment by nikolasburk** [comment]
Hi @bitIO, thanks a lot for opening this issue. That's a great point, I've just added a note to all "Get started" tutorials that shortly explain how to secure a Prisma server and link out the to `Authentication & Security` docs 🙏
