### ISSUE TITLE
Great way to get started with Graphql and react for the starter

### ISSUE THREAD

**Issue by drakata** [prisma/prisma-content-feedback#66]
**Article Title (if relevant)**
https://www.prisma.io/tutorials/build-react-graphql-app-with-fetch-ct19#enabling-authentication

**What did you find helpful in the article?*
Everything went smoothly, easy setup and entry into Graphql with React. Most online are outdated or too complicated.

**Comment by nikolasburk** [comment]
Hey @drakata, thanks a lot for your feedback! Great to hear the tutorial was helpful 🙌
