### ISSUE TITLE
Deploy Now example is outdated. Doesn't work with now v2

### ISSUE THREAD

**Issue by vasco3** [prisma/prisma-content-feedback#68]
**Article Title (if relevant)**
Provide the name and link to the article with the issue

**Describe the content issue**
A clear and concise description of what the issue with the content was

**Describe the solution you'd like to see**
How can this issue be resolved?

**Additional context**

**Comment by nikolasburk** [comment]
Hey @vasco3, thanks a lot for opening this issue 🙏 I've added a note to the beginning of the tutorial that it is currently outdated. We'll update it soon! 🙌
