### ISSUE TITLE
Prisma GraphQL API documentation is missing for version 1.28

### ISSUE THREAD

**Issue by jvlobo** [prisma/prisma-content-feedback#69]
I was looking for the documentation about raw database access but I couldn't find it. I've realized the section **Prisma GraphQL API** is gone now. I can see it at [1.27 version](https://www.prisma.io/docs/1.27/prisma-graphql-api/reference/raw-database-access-qwe4/#overview)

Why is that?

**Comment by nikolasburk** [comment]
Hey @jvlobo, thanks a lot for opening this issue.

we have indeed removed the docs for the Prisma GraphQL API in the latest docs versions. If you still to access them, you can (as you already found) still access them in older docs versions.

You can read the full motivation why we've removed the docs in [this](https://www.prisma.io/blog/prisma-and-graphql-mfl5y2r7t49c/) blog post. We're going to add more extensive docs for using `executeRaw` soon. 

Please let me know if you have any further questions, always happy to help! 🙂
