### ISSUE TITLE
Add a authentication example for Go client and gin

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-content-feedback#7]
**Article Title (if relevant)**
An example with Prisma client in Go and [gin](https://github.com/gin-gonic/gin) (HTTP framework).

**Describe the content issue**
There is no such example yet.

**Describe the solution you'd like to see**
An example that combines Prisma client in Go and gin. Preferably covers authentication as well.

**Additional context**
Original Forum thread: https://www.prisma.io/forum/t/add-a-go-graphql-auth-example-is-it-ok/4571?u=nilan.

**Comment by nikolasburk** [comment]
The need for this example is reflected in the `prisma-examples` repository: https://github.com/prisma/prisma-examples/issues/315
