### ISSUE TITLE
Tutorial example script is not correct

### ISSUE THREAD

**Issue by alanfeng99** [prisma/prisma-content-feedback#70]
**Article Title (if relevant)**
[Building an App part has wrong example code](https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-JAVASCRIPT-e001/)

**Describe the content issue**
The script for creating a user is not correct.

Run graphql query: 

```
mutation {
  createUser(name: "Bob") {
    id
  }
}
```

Got error

```
Error: Variable '$data' expected value of type 'UserCreateInput!' but got: {"name":"B"}. Reason: 'email' Expected non-null value, found null. (line 1, column 11):
```

Another incorrect query

```
mutation {
  publish(id: "__POST_ID__") {
    id
    title
    published
  }
}
```

Should be (id => postId)

```
mutation {
  publish(postId: "__POST_ID__") {
    id
    title
    published
  }
}
```

**Describe the solution you'd like to see**
The query should execute successfully.

**Additional context**
None

**Comment by nikolasburk** [comment]
Hey @alanfeng99, thanks a lot for opening this issue!

#### About your first error in `createUser`

First of all, it seems you have been using the JavaScript version of the "Getting Started"-tutorials, is that correct?

Please validate that your datamodel doesn't have a required `email` field, meaning there should be now exclamation mark behind the type `String`. Here's what the `User` model should look like:

```graphql
type User {
  id: ID! @unique
  email: String @unique # no exclamation mark here 
  name: String!
  posts: [Post!]!
}
```

If you don't have the exclamation mark and you still encounter the issue, you have found a bug in Prisma. Please [open an issue in the main repository](https://github.com/prisma/prisma/issues/new) then.

#### About your second error in `publish`

Just fixed it 🙂✅
