### ISSUE TITLE
Management secret docs improvement

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-content-feedback#72]
**Article Title (if relevant)**
Authentication & Security
https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/#management-api-token

**Describe the content issue**
The docs do not mention the use of `docker-compose up -d` command. 

**Describe the solution you'd like to see**
The docs should mention that after changing the `docker-compose.yml` file, we need to run `docker-compose up -d`

**Additional context**
![image](https://user-images.githubusercontent.com/746482/54534699-3599d080-498d-11e9-9856-052bb44d90c1.png)

**Comment by lunchboxer** [comment]
See this pull-request github.com/prisma/prisma/pull/4213

**Comment by nikolasburk** [comment]
I've added the info to the latest version of the docs. Thanks a lot for your help @lunchboxer 🙌
