### ISSUE TITLE
--boilerplate option to cli removed

### ISSUE THREAD

**Issue by vamshi9666** [prisma/prisma-content-feedback#73]
### --boilerplate option to cli not avaliable

 **steps to reproduce** : 

1. install prism and graphql-cli  `npm i -g prism graphql-cli`
2. create the project as in tutorial docs `graphql create my-app --boilerplate typescript-basic`

#### Error shown : 

Bootstrap a new GraphQL project
```

Options:
  --dotenv       Path to .env file                                      [string]
  -p, --project  Project name                                           [string]
  --no-install   Don't install project dependencies   [boolean] [default: false]
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]
Unknown argument: boilerplate

```

**Comment by vamshi9666** [comment]
was able to resolve this by not passing any options. Just used ` graphql create my-app  typescript-basic` 
then it lists all available boiler plates  , for which we need to select

**Comment by nikolasburk** [comment]
Hey @vamshi9666, thanks a lot for opening this issue. It seems like you have resolved it for now, I'm therefore closing this issue 🙏

**Comment by davisokoth** [comment]
@nikolasburk the docs seem to use the 'old' way, is this something that can be changed? Am assuming that [this](https://www.prisma.io/tutorials/bootstrap-a-graphql-server-in-typescript-ct09) is the official documentation...
I could submit a pr if so...
