### ISSUE TITLE
OMG, this is amazing!

### ISSUE THREAD

**Issue by nagman** [prisma/prisma-content-feedback#74]
**[Data Model](https://www.prisma.io/docs/1.16/develop-prisma-service/service-configuration/data-model-knul)**
You guys made an amazing work on this thing!

My life is 100 times simpler than before Prisma :smile: 

**What did you find helpful in the article?**
The docs are well made, and the design makes it easy to read and understand.

Noticed a few broken links, yet. But I can't find them again (this is a long page, you know).

**Comment by nikolasburk** [comment]
Thanks a lot for your feedback @nagman, this is great to hear! 🙌  Please let us know if you have any questions in the future, we're always happy to help!

**Comment by nikolasburk** [comment]
Also, we're currently testing a new datamodel version (v1.1) which is currently in beta. You can find all info for accessing it [here](https://github.com/prisma/datamodel-v1.1-feedback).
