### ISSUE TITLE
Some code samples not showing

### ISSUE THREAD

**Issue by newtmex** [prisma/prisma-content-feedback#75]
**Article Title (if relevant)**
https://www.prisma.io/docs/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4/

**Describe the content issue**
Code samples for TypeScript, JavaScript and GO not showing

**Describe the solution you'd like to see**
Let the codes show

**Comment by d3vhound** [comment]
Same issue here
<img width="750" alt="Screen Shot 2019-03-22 at 3 47 12 PM" src="https://user-images.githubusercontent.com/17565159/54852566-3c8d4f80-4cbb-11e9-8bf6-9864c16092be.png">
<img width="776" alt="Screen Shot 2019-03-22 at 3 47 06 PM" src="https://user-images.githubusercontent.com/17565159/54852567-3c8d4f80-4cbb-11e9-8974-52b0d30f4fc0.png">

**Comment by mickadoua** [comment]
on this doc to https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-TYPESCRIPT-t201/

**Comment by sweethuman** [comment]
They show if you're looking at version 1.27

**Comment by nikolasburk** [comment]
Thanks a lot for reporting this @newtmex, we just fixed the issue 🙌
