### ISSUE TITLE
Missing Instructions on tutorial page

### ISSUE THREAD

**Issue by LeonardoGentile** [prisma/prisma-content-feedback#77]
**Article Title (if relevant)**
https://www.prisma.io/docs/1.29/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/

**Describe the content issue**
Many code examples are missing (empty)

**Comment by webberwang** [comment]
Can't get started without the instructions

**Comment by nikolasburk** [comment]
Thanks a lot for reporting this @LeonardoGentile, we just fixed the issue 🙌
