### ISSUE TITLE
Prisma Deploy Watch Flag Not Recognized

### ISSUE THREAD

**Issue by Dmo16** [prisma/prisma-content-feedback#87]
https://www.prisma.io/docs/prisma-cli-and-configuration/cli-command-reference/prisma-deploy-xcv9/

The doc states you can run prisma deploy with -w or --watch 
When running this command in Ubuntu 18.04 command line it returns: 

> Unknown flag --watch
>Unknown flag -w

Depending on which you run of course.

I would suggest the docs be updated to remove the flag or include the proper one.

**Comment by nikolasburk** [comment]
Thanks for catching this @Dmo16 🙏 I've [just updated](https://github.com/prisma/prisma/pull/4444) the flags.
