### ISSUE TITLE
The example of the go client for count isn't written in go

### ISSUE THREAD

**Issue by alexdor** [prisma/prisma-content-feedback#88]
Hi, I've been trying to execute a `Count` operation, using the go client, but the example in the documentation is written in typescript not in go

https://github.com/prisma/prisma/blob/master/docs/1.31/prisma-client/basic-data-access/reading-data-GO-go05.mdx#examples-6

**Comment by nikolasburk** [comment]
Thanks a lot for reporting this @alexdor. Unfortunately aggregations are currently not supported in the Go client. I now updated the docs to reflect that. Since aggregations are implemented via (Relay) connections, the progress of aggregations can be tracked in this GitHub issue: https://github.com/prisma/prisma/issues/4027

**Comment by darmie** [comment]
## Temporary Solution
Use manual http connection, 
I haven't tested this with production endpoint tho...
```go
type UserConnection struct {
	Data struct {
		UsersConnection struct {
			Aggregate struct {
				Count int `json:"count,omitempty"`
			} `json:"aggregate,omitempty"`
		} `json:"usersConnection,omitempty"`
	} `json:"data,omitempty"`
}

func (r *queryResolver) UsersCount(ctx context.Context) (*ConnectionPayload, error) {
	query := `
	query{
		usersConnection{
		  aggregate{
			count
		  }
		}
	  }
	`
	body, _ := json.Marshal(map[string]string{
		"query": query,
	})

	resp, err := http.Post("http://localhost:4466/my-service/dev", "application/json", bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	data, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	res := UserConnection{}

	_ = json.Unmarshal(data, &res)

	return &ConnectionPayload{
		Count: res.Data.UsersConnection.Aggregate.Count,
	}, nil
}
```
