### ISSUE TITLE
Incorrect display of volume in docker-compose volume

### ISSUE THREAD

**Issue by CR1AT0RS** [prisma/prisma-content-feedback#89]
### Fix documentation docker-compose.yml

docker-compose  up
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 26, column 18

The last lines should be this:

```yml
volumes:
  postgres:
```

Prisma init generates docker-compose.yml correctly and also looks like its correct in Github too (https://github.com/prisma/prisma/blob/e5b2b56e55cfa99496c7163d53bbd6fa356976da/docs/1.15/get-started/01-setting-up-prisma-new-database-a002.mdx).

 I am not sure why it shows it incorrectly in the Documentation. Please correct this for mysql and mongoDB as well. Anyone who copies pastes this docker-compose.yml from here: https://www.prisma.io/docs/1.31/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/ gets this error. Fix should be fairly simple.

<img width="745" alt="Screen Shot 2019-04-25 at 12 41 43 AM" src="https://user-images.githubusercontent.com/4299288/56718094-fb8dbe00-66f2-11e9-8bfb-ddb0f7b5ffde.png">

**Comment by fandy** [comment]
👍 As someone who's new to Docker, this caused me some frustration. Thank you for creating the issue!

**Comment by beatrochee** [comment]
Thank you!! One slight change in the reporting of the issue (clear enough in the links @CR1AT0RS provided but just for anyone looking through the top-level text) -- the last lines should be:

<pre>
volumes:
  postgres:
</pre>

Github markdown was swallowing the whitespace creating the indentation :smile: but thank you for raising this, saved me a ton of time!

**Comment by nikolasburk** [comment]
Thanks a lot for reporting this @CR1AT0RS! This was an issue with prettier that we now fixed, you can find all further info in this PR: https://github.com/prisma/prisma/pull/4470

**Comment by CR1AT0RS** [comment]
Good work team!

**Comment by JaapWeijland** [comment]
Note: This error is also found in "[Deploy Prisma to DigitalOcean](https://www.prisma.io/tutorials/deploy-prisma-to-digitalocean-ct12)".

**Comment by santanuyogi** [comment]
Many many thanks! I could have been stuck on this for awhile as I'm not as familiar with this syntax as I probably should be.
