### ISSUE TITLE
broken link on "Connect Existing Database (Introspection)"

### ISSUE THREAD

**Issue by quinn** [prisma/prisma-content-feedback#92]
**Article Title (if relevant)**
[Connect Existing Database (Introspection)](https://www.prisma.io/docs/1.17/data-model-and-migrations/introspection-mapping-to-existing-db-soi1/)

**Describe the content issue**
this text:

![image](https://user-images.githubusercontent.com/3764/56995193-0a4ef780-6b6f-11e9-80b0-119795b31320.png)

The "known limitations" isn't a real link. 

**Describe the solution you'd like to see**

linking the text "known limitations" to an article that explains the known limitations.

**Comment by CR1AT0RS** [comment]
Known limitation is a real link: [https://github.com/prisma/prisma/issues/2377](url)

We can close out this issue. Not reproducible or someone already fixed it.

**Comment by nikolasburk** [comment]
@quinn Thanks a lot for opening this issue! 

The article you've linked is from Prisma `v1.17`. If you select the most recent version in the dropdown in the top-left corner of the docs (currently `v1.31`), you'll find that the limitations are fixed by now.

**Comment by quinn** [comment]
@nikolasburk thanks! thats what google pulled up when i searched, didn't notice it was versioned.

**Comment by nikolasburk** [comment]
That's what I thought. We're currently working on improving SEO for our docs, so hopefully in the future you'll automatically land on the latest versions 🙌
