### ISSUE TITLE
Conflicting reference to Secret environment variable

### ISSUE THREAD

**Issue by kshenes** [prisma/prisma-content-feedback#93]
**Article Title (if relevant)**
Authentication & Security
https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/

**Describe the content issue**
The documentation is using conflicting naming of the environment variable required to use Secrets
In one spot: PRISMA_MANAGEMENT_SECRET
else were in docs:  PRISMA_MANAGEMENT_API_SECRET

**Describe the solution you'd like to see**
How can this issue be resolved?
Accurately document what is required by the end user to make prisma work. Giving incorrect and conflicting information costs your adopters lots of wasted time.

**Additional context**

**Comment by nikolasburk** [comment]
Thanks for pointing this out @kshenes! I've just fixed the issues, the env var is called `PRISMA_MANAGEMENT_API_SECRET `
