### ISSUE TITLE
MANAGEMENT_API_SECRET in Prisma Server - Authentication & Security should be PRISMA_MANAGEMENT_API_SECRET

### ISSUE THREAD

**Issue by haysclark** [prisma/prisma-content-feedback#97]
Prisma Server - Authentication & Security
https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/#prisma-server

The text uses `PRISMA_MANAGEMENT_SECRET` environment variable in this sentence:
  > After that, you'll need to use the environment variable PRISMA_MANAGEMENT_SECRET to authenticate with the Management API from the Prisma CLI, learn more here.

Should be `PRISMA_MANAGEMENT_API_SECRET`:
  > After that, you'll need to use the environment variable PRISMA_MANAGEMENT_API_SECRET to authenticate with the Management API from the Prisma CLI, learn more here.

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @haysclark, I've just fixed the issue! 🙌

**Comment by dakotalightning** [comment]
Kind poke,

I think the old version is still there.
https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/

I spent a good 20 min trying to figure out why it wasn't working, then reread it again and found `PRISMA_MANAGEMENT_API_SECRET`
