### ISSUE TITLE
Writing Data (JavaScript)

### ISSUE THREAD

**Issue by gillianbc** [prisma/prisma-content-feedback#98]
**Writing Data (JavaScript)**
https://www.prisma.io/docs/prisma-client/basic-data-access/writing-data-JAVASCRIPT-rsc6/

**Describe the content issue**
The headers start saying 'Typescript' half way down the page

**Describe the solution you'd like to see**
Correct the titles to say javascript

**Comment by nikolasburk** [comment]
Fixed ✅ thanks a lot for catching this! 🙏
