### ISSUE TITLE
Link broken. Data Import & Export

### ISSUE THREAD

**Issue by alan345** [prisma/prisma-content-feedback#99]
**Article Title (if relevant)**
Provide the name and link to the article with the issue
Data Import & Export: https://www.prisma.io/docs/prisma-cli-and-configuration/data-import-and-export-jsw9/

**Describe the content issue**
A clear and concise description of what the issue with the content was
Link broken

**Describe the solution you'd like to see**
How can this issue be resolved?
Change the URL of the sentence: `In the future, the Prisma CLI will support importing from these data sources directly.`

URL: https://github.com/graphcool/framework/issues/1410 is broken. 404 error

**Additional context**
![image](https://user-images.githubusercontent.com/15246526/58040822-4aa8f200-7aeb-11e9-8497-4a33f38c994e.png)

**Comment by nikolasburk** [comment]
Hey @alan345, thanks a lot for opening this issue. I currently can't reproduce the issue, the link you're mentioning points to `https://github.com/prisma/prisma/issues/1410` which is the correct link. Is it possible that you're looking at an older docs version (rather than the latest one)?
